inherit_from: "configs/mono/tum/base_config.yaml"

Dataset:
  dataset_path: "/home/hsieh/Codes/Dataset/endomapper_simulator_dataset/Seq_1_monogs"
  # dataset_path: "/home/hsieh/Codes/Dataset/endomapper_simulator_dataset/endomapper_seq1_monogs"
  Calibration:
    fx: 472.64955100886374
    fy: 472.64955100886374
    cx: 479.5
    cy: 359.5
    k1: 0.0
    k2: 0.0
    p1: 0.0
    p2: 0.0
    k3: 0.0
    width: 960
    height: 720
    # depth_scale: 5000.0
    distorted: False
